version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: SA_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - sa_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: SA_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - sa_network

volumes:
  postgres_data:

networks:
  sa_network:
    driver: bridge